# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 300, 521, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuConfigure_Devices = QtWidgets.QMenu(self.menubar)
        self.menuConfigure_Devices.setObjectName("menuConfigure_Devices")
        self.menuAdd_Device = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Device.setObjectName("menuAdd_Device")
        self.menuDevice_List = QtWidgets.QMenu(self.menubar)
        self.menuDevice_List.setObjectName("menuDevice_List")
        self.menuDashboard = QtWidgets.QMenu(self.menubar)
        self.menuDashboard.setObjectName("menuDashboard")
        self.menuToggle = QtWidgets.QMenu(self.menubar)
        self.menuToggle.setObjectName("menuToggle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuConfigure_Devices.menuAction())
        self.menubar.addAction(self.menuAdd_Device.menuAction())
        self.menubar.addAction(self.menuDevice_List.menuAction())
        self.menubar.addAction(self.menuDashboard.menuAction())
        self.menubar.addAction(self.menuToggle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Usin pyqt graph the power consumption graph will be plotted in here"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuConfigure_Devices.setTitle(_translate("MainWindow", "Configure Devices"))
        self.menuAdd_Device.setTitle(_translate("MainWindow", "Add Device"))
        self.menuDevice_List.setTitle(_translate("MainWindow", "Device List"))
        self.menuDashboard.setTitle(_translate("MainWindow", "Dashboard"))
        self.menuToggle.setTitle(_translate("MainWindow", "Toggle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
